<?php

namespace App\Services;

use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;

/** Derives the app's notifications from the current task list. */
class TaskAlertsService
{
    /** Minutes before its deadline at which an unfinished task is flagged as due soon. */
    public const DUE_SOON_WINDOW_MINUTES = 60;

    /** How far back to keep warning about missed deadlines, in days. */
    public const OVERDUE_GRACE_DAYS = 7;

    public const COMPLETED_PREFIX = 'task-completed-';

    public const DUE_SOON_PREFIX = 'task-due-soon-';

    public const OVERDUE_PREFIX = 'task-overdue-';

    /** Every key prefix this service generates. @return list<string> */
    public static function managedPrefixes(): array
    {
        return [
            self::COMPLETED_PREFIX,
            self::DUE_SOON_PREFIX,
            self::OVERDUE_PREFIX,
        ];
    }

    /** Whether a stored alert key was generated by this service. */
    public static function isManagedKey(string $key): bool
    {
        foreach (self::managedPrefixes() as $prefix) {
            if (str_starts_with($key, $prefix)) {
                return true;
            }
        }

        return false;
    }

    /** @return list<array{key: string, message: string, is_success: bool, group: string}> */
    public function desiredAlerts(Collection $tasks, Carbon $now): array
    {
        $alerts = [];

        foreach ($tasks as $task) {
            if ($task->isComplete()) {
                $alerts[] = [
                    'key' => self::COMPLETED_PREFIX.$task->id,
                    'message' => 'Nice work — you finished "'.$task->title.'".',
                    'is_success' => true,
                    'group' => self::groupFor($now, $now),
                ];

                continue;
            }

            $deadline = $task->deadline;

            if ($now->isAfter($deadline)) {
                // Stop nagging about deadlines from the distant past.
                if ($now->diffInSeconds($deadline) > self::OVERDUE_GRACE_DAYS * 86400) {
                    continue;
                }

                $alerts[] = [
                    'key' => self::OVERDUE_PREFIX.$task->id,
                    'message' => '"'.$task->title.'" was due '
                        .self::mediumDate($task->date).' at '.$task->end_time.'.',
                    'is_success' => false,
                    'group' => self::groupFor($now, $now),
                ];
            } elseif ($deadline->diffInSeconds($now) <= self::DUE_SOON_WINDOW_MINUTES * 60) {
                $alerts[] = [
                    'key' => self::DUE_SOON_PREFIX.$task->id,
                    'message' => 'Time is running out — "'.$task->title.'" '
                        .'is due at '.$task->end_time.'.',
                    'is_success' => false,
                    'group' => self::groupFor($now, $now),
                ];
            }
        }

        return $alerts;
    }

    /** Reconciles the user's stored alerts with the set implied by their tasks. */
    public function syncForUser(User $user, ?Carbon $now = null): void
    {
        $now ??= Carbon::now();

        $tasks = $user->tasks()->get();
        $desired = $this->desiredAlerts($tasks, $now);
        $desiredKeys = array_column($desired, 'key');

        // Retire managed alerts whose cause has disappeared.
        $user->alerts()
            ->where(fn ($query) => $query
                ->where('key', 'like', self::COMPLETED_PREFIX.'%')
                ->orWhere('key', 'like', self::DUE_SOON_PREFIX.'%')
                ->orWhere('key', 'like', self::OVERDUE_PREFIX.'%'))
            ->whereNotIn('key', $desiredKeys)
            ->delete();

        // Insert only the genuinely new ones, leaving existing records alone.
        $existingKeys = $user->alerts()->pluck('key')->all();

        foreach ($desired as $attributes) {
            if (! in_array($attributes['key'], $existingKeys, true)) {
                $user->alerts()->create($attributes);
            }
        }
    }

    /** Human grouping for the alerts list: "Today", "Yesterday", or a date. */
    public static function groupFor(Carbon $when, Carbon $now): string
    {
        $difference = $now->copy()->startOfDay()->diffInDays($when->copy()->startOfDay(), false);

        if ($difference <= 0) {
            return 'Today';
        }

        if ($difference === 1) {
            return 'Yesterday';
        }

        return self::mediumDate($when);
    }

    /** Formats a date as e.g. "Oct 24th, 2023". */
    public static function mediumDate(Carbon $date): string
    {
        return $date->format('M jS, Y');
    }
}
