<?php

namespace App\Services;

use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;

/**
 * Derives the app's notifications from the current task list.
 *
 * This is a faithful port of the Flutter app's `TaskAlertsService`. Alerts are
 * *derived*, not created by hand: a completed task earns a congratulation, a
 * task running out of time earns a "due soon" warning, and an overdue task
 * earns an "overdue" warning. The service then *reconciles* the alerts table so
 * it always matches the desired set — nothing is appended blindly, so re-running
 * the scan can't duplicate alerts, and an alert disappears on its own once its
 * cause does (finishing an overdue task clears its warning and leaves a
 * congratulation in its place).
 */
class TaskAlertsService
{
    /**
     * How close to its deadline an unfinished task must be before it is flagged
     * as running out of time.
     */
    public const DUE_SOON_WINDOW_MINUTES = 60;

    /**
     * How far back to keep warning about missed deadlines. Without this, a
     * months-old list would bury the user in overdue alerts.
     */
    public const OVERDUE_GRACE_DAYS = 7;

    public const COMPLETED_PREFIX = 'task-completed-';

    public const DUE_SOON_PREFIX = 'task-due-soon-';

    public const OVERDUE_PREFIX = 'task-overdue-';

    /**
     * Every key prefix this service generates. Alerts whose key starts with any
     * of these are "managed" and may be retired during reconciliation; anything
     * else is left alone.
     *
     * @return list<string>
     */
    public static function managedPrefixes(): array
    {
        return [
            self::COMPLETED_PREFIX,
            self::DUE_SOON_PREFIX,
            self::OVERDUE_PREFIX,
        ];
    }

    /**
     * Whether a stored alert key was generated by this service.
     */
    public static function isManagedKey(string $key): bool
    {
        foreach (self::managedPrefixes() as $prefix) {
            if (str_starts_with($key, $prefix)) {
                return true;
            }
        }

        return false;
    }

    /**
     * The complete set of task-driven alerts implied by `$tasks` at `$now`.
     *
     * Each entry is an attribute array ready to be passed to Alert::create() —
     * note it carries a deterministic `key` (used for reconciliation) but no
     * `id`, which Eloquent generates as a UUID on insert.
     *
     * @param  Collection<int, Task>  $tasks
     * @return list<array{key: string, message: string, is_success: bool, group: string}>
     */
    public function desiredAlerts(Collection $tasks, Carbon $now): array
    {
        $alerts = [];

        foreach ($tasks as $task) {
            if ($task->isComplete()) {
                $alerts[] = [
                    'key' => self::COMPLETED_PREFIX.$task->id,
                    'message' => 'Nice work — you finished "'.$task->title.'".',
                    'is_success' => true,
                    'group' => self::groupFor($now, $now),
                ];

                continue;
            }

            $deadline = $task->deadline;

            if ($now->isAfter($deadline)) {
                // Stop nagging about deadlines from the distant past.
                if ($now->diffInSeconds($deadline) > self::OVERDUE_GRACE_DAYS * 86400) {
                    continue;
                }

                $alerts[] = [
                    'key' => self::OVERDUE_PREFIX.$task->id,
                    'message' => '"'.$task->title.'" was due '
                        .self::mediumDate($task->date).' at '.$task->end_time.'.',
                    'is_success' => false,
                    'group' => self::groupFor($now, $now),
                ];
            } elseif ($deadline->diffInSeconds($now) <= self::DUE_SOON_WINDOW_MINUTES * 60) {
                $alerts[] = [
                    'key' => self::DUE_SOON_PREFIX.$task->id,
                    // Deliberately not "due in 42 minutes": the alert is written
                    // once and kept, so a countdown baked into the text would
                    // go stale.
                    'message' => 'Time is running out — "'.$task->title.'" '
                        .'is due at '.$task->end_time.'.',
                    'is_success' => false,
                    'group' => self::groupFor($now, $now),
                ];
            }
        }

        return $alerts;
    }

    /**
     * Reconciles the user's stored alerts with the set implied by their tasks.
     *
     * Managed alerts whose cause has gone away are deleted; genuinely new ones
     * are inserted; existing ones (and anything this service did not create)
     * are left untouched so their read state survives.
     */
    public function syncForUser(User $user, ?Carbon $now = null): void
    {
        $now ??= Carbon::now();

        $tasks = $user->tasks()->get();
        $desired = $this->desiredAlerts($tasks, $now);
        $desiredKeys = array_column($desired, 'key');

        // 1. Retire managed alerts whose cause has disappeared.
        $user->alerts()
            ->where(fn ($query) => $query
                ->where('key', 'like', self::COMPLETED_PREFIX.'%')
                ->orWhere('key', 'like', self::DUE_SOON_PREFIX.'%')
                ->orWhere('key', 'like', self::OVERDUE_PREFIX.'%'))
            ->whereNotIn('key', $desiredKeys)
            ->delete();

        // 2. Insert only the genuinely new ones, leaving existing records alone
        //    (so their is_read flag and timestamps are preserved).
        $existingKeys = $user->alerts()->pluck('key')->all();

        foreach ($desired as $attributes) {
            if (! in_array($attributes['key'], $existingKeys, true)) {
                $user->alerts()->create($attributes);
            }
        }
    }

    /**
     * Human grouping for the alerts list: "Today", "Yesterday", or a date.
     */
    public static function groupFor(Carbon $when, Carbon $now): string
    {
        $difference = $now->copy()->startOfDay()->diffInDays($when->copy()->startOfDay(), false);

        if ($difference <= 0) {
            return 'Today';
        }

        if ($difference === 1) {
            return 'Yesterday';
        }

        return self::mediumDate($when);
    }

    /**
     * Formats a date the way the frontend's "medium" format does, e.g.
     * "Oct 24th, 2023".
     */
    public static function mediumDate(Carbon $date): string
    {
        return $date->format('M jS, Y');
    }
}
